### ISSUE TITLE
[Request] More packs - burnedfx, AutoReiv, and Rally Ho!

### ISSUE THREAD

**Issue by txtsd** [DFgraphics/DFgraphics#15]
These packs have really nice graphics and it would be amazing if DFgraphics could include them!

- [x] [burnedfx](http://www.bay12forums.com/smf/index.php?topic=143588)
- [x] [AutoReiv](http://www.bay12forums.com/smf/index.php?topic=152432)
- [x] [Rally Ho!](http://www.bay12forums.com/smf/index.php?topic=149172)
- [x] [Wanderlust Mini](http://dffd.bay12games.com/file.php?id=11443) [12x12 version]

**Comment by Rydelfox** [comment]
As the creator of Rally Ho, I'm absolutely down for this.
I'll be working on standardizing Rally Ho with Quiet-sun's standardizer this evening and create a manifest.json

I'll hopefully be able to submit it within the next day or so.

**Comment by PeridexisErrant** [comment]
OK - revisiting some issues, now that we have enough people to be a little more active here.
Generally anything with creature graphics + tileset + colors is eligible, so all of these fit.  Also polite to only rehost with permission or when no first-author updates are happening anymore.

- [ ] @Rydelfox - if you're interested in moving the Rally Ho! repo here, I can create a copy and give you admin over it.
- [ ] burnedfx - I'll ask burned about it, same deal as above
- [ ] AutoReiv - last update 40.24; author not logged in since April.  Will still ask, but won't wait too long.
- [ ] wanderlust - looks like a simple case of adding tilesets to me, since the creature graphics in that are still 16x16

**Comment by Rydelfox** [comment]
I am interested.

**Comment by PeridexisErrant** [comment]
@DFgraphics/rally-ho-team now exists; @Rydelfox you now have control of https://github.com/Rydelfox/Rally-Ho - thanks!

AutoReiv also replied and is keen to join, so I'll be helping with that soon.

**Comment by IggyTheAutoReiv** [comment]
Hi guys! Thanks for letting me in! I've just uploaded my pack to the repo. It took some finagling, but everything should be in something resembling an order I think.

**Comment by PeridexisErrant** [comment]
Spoke with Burned, who asked not to have their graphics included.  2f5927fd shows that Fricy had a similar conversation!

And that's the last of the packs mentioned, so issue closed :)
